# Generated by Django 1.11.5 on 2017-09-20 13:25
from typing import Any, List

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'password',
                    models.CharField(
                        max_length=128,
                        verbose_name='password'
                    )
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='last login'
                    )
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        verbose_name='email address to login'
                    )
                ),
                ('name', models.CharField(max_length=25, verbose_name='닉네임')),
                ('exp', models.IntegerField(default=0, verbose_name='경험치')),
                (
                    'tz',
                    timezone_field.fields.TimeZoneField(
                        default='Asia/Seoul',
                        verbose_name='Timezone'
                    )
                ),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                (
                    'date_joined',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='회원가입일'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
